linters:
  enable-all: false
  disable-all: true
  enable:
    - depguard
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - typecheck
    - unconvert
    - unparam
    - unused
    - exportloopref
    - staticcheck

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  skip-dirs-use-default: false
