# [3/3] RUN echo hi
- type: EXEC
  args: [/bin/sh, -c, echo hi]
  env: ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin']
  cwd: /tmp
  user: nobody
  mounts:
    - mountpoint: /
      type: BIND
      output: 0
      input:
        # [2/3] WORKDIR /tmp
        type: FILE
        actions:
            - type: MKDIR
              path: /tmp
              mode: "0o755"
              create-parents: true
              owner:
                user: nobody
              input:
                # [1/3] FROM docker.io/library/busybox@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
                type: SOURCE
                source: docker-image://docker.io/library/busybox@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
                platform: linux/arm64
